social_media_analysis:
  description: >
    Analyze {csv_file} using CSV search tool to identify:
    1. Top-performing content types like static posts or reels and video content
    2. Engagement patterns based on whether its a blog post or a job post or any other related post type
    3. Which Social media had the best outcome for a certain type of content
  expected_output: >
    Comprehensive analysis report with key metrics in markdown format that can be use to come to conclusions on how to plan the next weeks social media strategy
  async_execution: true
  agent: historical_data_analyst