data_analysis:
  description: >
    Analyze {csv_file} using CSV search tool to identify:
    1. Top-performing content types
    2. Engagement patterns
    3. Audience demographics
  expected_output: >
    Comprehensive analysis report with key metrics in markdown format
  agent: data_analyst


trend_research:
  description: >
    Research current {industry} trends including platform-specific formats,
    seasonal opportunities, and competitor strategies to make sure {company} get's the best Social Media plan
  expected_output: >
    Detailed trend report with ranked content recommendations
  agent: trend_researcher

strategy_development:
  description: >
    Create 30-day content calendar incorporating analysis insights and
    trend research while following {brand_guidelines}
  expected_output: >
    Multi-platform content calendar with posting schedule and format breakdown
  agent: content_strategist

content_creation:
  description: >
    Generate platform-specific assets including captions, scripts, and
    visual concepts aligned with {brand_voice}
  expected_output: >
    Complete content package with 20+ production-ready assets
  agent: content_creator

quality_assurance:
  description: >
    Verify content quality, brand voice consistency, and engagement potential
    through rigorous testing protocols
  expected_output: >
    Polished content package with QA report and improvement suggestions
  agent: quality_controller
